name: Deploy main (CI)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm ci

      - name: Testes
        run: npm run test

      - name: Testes (e2e)
        run: npm run test:e2e

      - name: Build TypeScript
        run: npm run build
